services:
  #Nginx Service
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "8081:80"
      - "443:443"
    restart: always
    networks:
      - docker-network
    # env_file:
    # - .env
networks:
    # network name
    docker-network:
      # ip address management
      ipam:
        driver: default
        config:
          - subnet: "192.168.92.0/24"

  
