services:
  # Nginx Service
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - docker-network
    env_file:
    - .env
      #volumes:
      #- /home/ohladkov/data/html:/var/www/html
        # - /home/ohladkov/data/nginx.conf:/etc/nginx/nginx.conf
  
  # Database mariadb
  db:
    image: mariadb
    container_name: mariadb
    volumes:
      - /home/ohladkov/data/mysql:/var/lib/mysql
    env_file: 
      - .env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        #MARIADB_ROOT_PASSWORD_FILE: '${MYSQL_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MYSQL_DATABASE}'
      MARIADB_USER: '${MYSQL_USER}'
      NARISDB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    restart: always

  # Wordpress
  wordpress:
    # to create mysql first
    depends_on:
      - db
    image: wordpress:php8.0-fpm-alpine #wordpress:latest
    container_name: wordpress
    volumes:
      - /home/ohladkov/data/html:/var/www/html

        #ports:
        #  - '80:80'
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER:  '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_password
    networks:
      - docker-network
    restart: always
  
  # GUI for mariadb
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
         # To use the CLI to access mariadb dir:
  # dokcer exec -it mariadb mysql --user=root --password=(password)
  # 

networks:
    # network name
    docker-network:
      # ip address management
      ipam:
        driver: default
          #        config:
          #- subnet: "192.168.92.0/24"
volumes:
  data-html:
    #  data-nginx-conf:
secrets:
  inception_secrets:
    file: ./secrets/credentials.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt


# https://docs.docker.com/compose/use-secrets/
