services:

  # Nginx Service
  nginx_inception:
    depends_on:
      - wordpress_inception
      - adminer_inception
    build: 
      context: requirements/nginx/
      dockerfile: Dockerfile
    image: nginx_inception
    container_name: nginx_inception
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - v_wordpress:/var/www/html
    networks:
      - inception

  # Database mariadb
  mariadb_inception:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb_inception
    container_name: mariadb_inception
    restart: unless-stopped
    volumes:
      - v_mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception

  # Wordpress
  wordpress_inception:
    depends_on:
      - mariadb_inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress_inception
    container_name: wordpress_inception
    restart: unless-stopped
    volumes:
      - v_wordpress:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    secrets:
       - db_root_password
       - db_password
       - credentials
    networks:
      - inception

  # redis for cache management
  redis_inception:
    depends_on:
      - wordpress_inception
    container_name: redis_inception
    build:
      context: requirements/bonus/redis/
      dockerfile: Dockerfile
    image: redis_inception
    restart: always
    env_file:
      - .env
    networks:
      - inception

  # adminer GUI for mariadb
  adminer_inception:
    build:
      context: requirements/bonus/adminer/
      dockerfile: Dockerfile
    container_name: adminer_inception
    image: adminer_inception
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception

networks:
    inception:
      name: inception
      driver: bridge

volumes:
  v_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ohladkov/data/wordpress'
  v_mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/ohladkov/data/mariadb'

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
