services:
  
  # Database mariadb
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    # image: mariadb/srcs_mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - v_mariadb:/var/lib/mysql
    env_file:
      - .env
    # stdin_open: true
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception

  # Wordpress
  wordpress:
    depends_on:
      - mariadb
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    # image: wordpress/srcs_wordpress
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - v_wordpress:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    secrets:
       - db_root_password
       - db_password
    networks:
      - inception

  # Nginx Service
  nginx:
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx/
      dockerfile: Dockerfile
    # image: nginx/srcs_nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - v_wordpress:/var/www/html
    networks:
      - inception
  
  # GUI for mariadb
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
    # To use the CLI to access mariadb dir:
  # dokcer exec -it mariadb mysql --user=root --password=(password)
  # 

  redis:
    depends_on:
      - wordpress
    container_name: redis
    build:
      context: requirements/bonus/redis/
      dockerfile: Dockerfile
    image: redis/srcs-redis
    restart: always
    # volumes:
    #   - redis_data:/var/lib/redis
    env_file:
      - .env
    networks:
      - inception
      # in wp-config.php file.
# define('WP_REDIS_HOST', 'redis');
# define('WP_REDIS_PORT', '6379');

# define( 'WP_REDIS_PATH', '/var/run/redis/redis.sock' );
# define( 'WP_REDIS_SCHEME', 'unix' );

networks:
    inception:
      name: inception
      driver: bridge

volumes:
  v_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/wordpress'
      # device: '/home/ohladkov/data/wordpress'
  v_mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: './data/mariadb'
  # redis_data:
  #   driver: local
  #   driver_opts:
  #     type: 'none' 
  #     o: 'bind'
  #     device: './data/redis'
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt


# https://docs.docker.com/compose/use-secrets/
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose

