services:
  
  # Database mariadb
  mariadb:
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount initialization scripts
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: db_root_password
      MARIADB_DATABASE: '${DATABASE_NAME}'
      MARIADB_USER: '${MYSQL_USER}'
      MARIADB_PASSWORD_FILE: db_password
    tty: true #docker start -i mariadb
    stdin_open: true
    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception

  # Wordpress
  wordpress:
    # to create mysql first
    depends_on:
      - mariadb
    # image: wordpress:php8.0-fpm-alpine #wordpress:latest
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - ./data/wp:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
      WORDPRESS_DB_USER:  '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD_FILE: db_password
    secrets:
       - db_password
    networks:
      - inception

  # Nginx Service
  nginx:
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./data/wp-content:/var/www/html/content
    networks:
      - inception
  
  # GUI for mariadb
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
    # To use the CLI to access mariadb dir:
  # dokcer exec -it mariadb mysql --user=root --password=(password)
  # 

networks:
    # network name
    inception:
      # ip address management
      ipam:
        driver: default
          #        config:
          #- subnet: "192.168.92.0/24"
volumes:
  html-data:
#  wordpress:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/home/ohladkov/data/wordpress'
#  mariadb:
#    driver: local
#    driver_opts:
#      type: 'none' 
#      o: 'bind'
#      device: '/home/ohladkov/data/mariadb'
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt


# https://docs.docker.com/compose/use-secrets/
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose

