services:
  # Wordpress
  wordpress:
    # to create mysql first
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - /home/ohladkov/data/html:/var/www/html
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - inception

  # Database
  db:
    image: mysql:8.0
      #command: '--default-autentication-plugin=mysql_native_password'
    environment:
      DATABASE_NAME: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      # Mapping host directory to container directory
      - /home/ohladkov/data/mysql:/var/lib/mysql
    restart: always
    networks:
      - inception

networks:
  inception:
    #ipam:
     driver: default
    # config:
    #   - subnet: "10.56.1.0/24"

volumes:
  #/data/mysql:
  html-data:



